### ISSUE TITLE
Resolvers

### ISSUE THREAD

**Issue by ohmichael** [dobbelina/repository.dobbelina#1]
Alot of them dont resolve but its a start

**Comment by ohmichael** [comment]
Try playing a few of them like daftsex

**Comment by deanogers** [comment]
The scenes don’t work in watchxxxfree and porntrex can u fix please

**Comment by jdoedev123** [comment]
Porntrex is not working because the code is shared with JAVWhores. I would suggest splitting the code.

**Comment by ohmichael** [comment]
Daftsex and porntrex are the main ones

**Comment by jdoedev123** [comment]
[porntrex.zip](https://github.com/dobbelina/repository.dobbelina/files/2798424/porntrex.zip)

**Comment by jdoedev123** [comment]
Proposed fix

**Comment by stemei2013** [comment]
When you do a search on porntrex, only one page with results is displayed. if you click on "Next page (2)" for example, the same results are displayed again. so you never get to page 2 (or 3 etc).
Maybe you can fix that too?
Thanks then the great work btw

**Comment by jdoedev123** [comment]
Proposed PornTrex fix with Search Pagination in Porntrex and JavWhores

[porntrex.zip](https://github.com/dobbelina/repository.dobbelina/files/2824122/porntrex.zip)

**Comment by dobbelina** [comment]
Nice!
Thanks for the fix.

**Comment by Spall01** [comment]
First of all, thanks for your awesome work. There is also a problem with YourPorn. It doesn't show any videos. Maybe you can also fix it.
Thanks

**Comment by jdoedev123** [comment]
Before I found 1.1.65 here I had my own fixes for a number of sites. But have since concentrated on only the most popular broken sites. Not wishing to duplicate work done elsewhere. Took a look at YourPorn and have a very preliminary version that displays scenes but does not play videos. May get back to it eventually.
For Reddit Community discussions on latest UWC fixes see:
https://www.reddit.com/r/Addons4Kodi/comments/a0owsw/ultimate_whitecream_can_anyone_fix/?sort=confidence

**Comment by ohmichael** [comment]
Daftsex not listed

**Comment by jdoedev123** [comment]
Proposed PornTrex fix for missing images.
[porntrex.py.zip](https://github.com/dobbelina/repository.dobbelina/files/2843969/porntrex.py.zip)
