### ISSUE TITLE
https://www.naughtyblog.org/pornstar/mia-trejsi/

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#1052]
The site needs premium.subscriprion for watching content even in HD. Please check yourself. Meanwhile, high quality similar content is available  free on
http://www.incestflix.com
http://www.incestflix.com/dmca

**Comment by ErosVece** [comment]
In any case, it is advisable to get a service such as Real-Debrid in combination with Cumination.
With RD you can at least play the Rapidgator links on Naughtyblog.

Keep2Share is different, it is not supported by many services. I'm currently testing Boxbit.app, but even that has a 5GB limit per day.
But, I'm thinking about taking a Keep2share membership, it's like $10 or something. Naughtyblog has many many siterips (all K2S links), it will be fun to browse that for a few days :)

**Comment by imurreflection** [comment]
Agreed on everything but do we have a concept of adding pure pay-sites in cumination? I know we have pornhub but even that is not premium enabled.

**Comment by Gujal00** [comment]
K2S is one of most expensive premium service out there

Premium - 10,000 Mb daily from $13.00/month
Premium Pro - 50,000 Mb daily from $16/month

so even with Premium you are stuck with 10GB (or 50GB for Premium Pro) a day limit so downloading a 400GB file is an issue

**Comment by imurreflection** [comment]
@ErosVece did you notice that playback stalls at 6.50 and then completely stop. Why do we want to have a site doest play more than 7 mins.

**Comment by ErosVece** [comment]
@imurreflection , no...because I only tested the k2s resolve playback for playing and skipping forward.

Why don't we want to have a site that works fine for people with for example Real-Debrid (who want to pay around $3 per month for more and better links in Kodi), but not for the others?
There are 100+ other sites in Cumination they can use.

There is another site I've come across, seaporn.org....the videos have k2s, nitroflare and rapidgator links.
