### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by firetrap71** [dobbelina/repository.dobbelina#1055]
Still not working iv updated to 1.1.77 and nothing

**Comment by ErosVece** [comment]
Provide a (debug) log, and we can have a look what or why.

**Comment by firetrap71** [comment]
Don't no if done right form dubug log 
![IMG_20230528_202917_HDR](https://github.com/dobbelina/repository.dobbelina/assets/30598218/a457613c-47c9-440a-821c-e5d1b68488a7)

**Comment by firetrap71** [comment]
Can you tell me why you have closed this as you have not told me if I done right

**Comment by ErosVece** [comment]
Ah, I see what's going on. You run an older Kodi with Python 2.7.
It looks like there's in the awmnetwork file a Python 3 only code.
I'll fix it.

**Comment by firetrap71** [comment]
Ok thanks

**Comment by firetrap71** [comment]
1.1.74 works but 1.1.77 does not work I'm using Kodi 18.9

**Comment by notimp** [comment]
next python three error is hentai-moon.py line 65 stil not fixed

**Comment by ErosVece** [comment]
It's done https://github.com/dobbelina/repository.dobbelina/commit/fdbf803e8a80f19f968194ab8dde14dcfdfb924c

**Comment by notimp** [comment]
> It's done [fdbf803](https://github.com/dobbelina/repository.dobbelina/commit/fdbf803e8a80f19f968194ab8dde14dcfdfb924c)

thunbs up. :)

Oh, and btw the Ividz addon broke a few days ago. Still broken in .77 :)

**Comment by firetrap71** [comment]
Any fix with the issue I'm having.thanks

**Comment by dobbelina** [comment]
Sorry, i closed this thread by mistake, re-opening.
Just closed another thread named "Nothing working"

**Comment by ramjam720** [comment]
I am having the same problem as firetrap71.  I received an update from 1.74 to 1.77, and now the addon does not launch.

**Comment by whatsuprob** [comment]
I went to Kodi\addons\plugin.video.cumination\resources\lib\exception_logger.py
and deleted line 23 (below).

from typing import Text, Callable, Generator

Saved the exception_logger.py file and cumination opened and appears to be working for me on Kodi 18.9 windows 10 and android 9.

**Comment by ErosVece** [comment]
> 

What version are you running, and on what system?
I have no problems here on Kodi 20 and 19, with the typing import.

**Comment by Joexxx1** [comment]
All this tech talk is over my head. Haha
I run Kodi 18.9 on my Sony TV. 

Is there an ETA on a regular fix update?

I appreciate the work being done! Thank you!

**Comment by whatsuprob** [comment]
> 

I'm using the latest version, 1.77 or whatever it is, and the nightly release directly inside the repo and I'm running it on Kodi 18.9 windows and android. From what I read it seems like this is a Kodi 18 only issue due to python 3 coding in the latest version.

**Comment by ErosVece** [comment]
> > 
> 
> I'm using the latest version, 1.77 or whatever it is, and the nightly release directly inside the repo and I'm running it on Kodi 18.9 windows and android. From what I read it seems like this is a Kodi 18 only issue due to python 3 coding in the latest version.

Sorry, my bad. Somehow I thought that Kodi 19 also was on Python 2.7 🤣 
Yes, it is a Py2 thing :)

Why not upgrade to Kodi 19 (or 20?)

**Comment by whatsuprob** [comment]
Super favourites and other vital tools for me like repo check, addon search, etc  are glitchy or garbage on 19 and 20.

**Comment by losthelp815** [comment]
Just wondering im also facing this issue using Kodi 18.0 on Nividas Shield TV Os and Cummnation will not load as of latest update. Will this be resolved in a new update? Or do we have to move on to Kodi 19 or 20.

**Comment by ErosVece** [comment]
I'll see if it's possible to make it Python 2 compatible.
It not, I can just let it skip it :)

In my opinion it's better to move to Kodi 20.

**Comment by whatsuprob** [comment]
> Here, I installed Kodi 18.9 on Windows, and this works there: [24d0b16](https://github.com/dobbelina/repository.dobbelina/commit/24d0b163d679b2f1b9b72b5f0592f3ce4dbabc29)
> 
> In my opinion it's better to move to Kodi 20 :)

Works great for me on both Kodi 18.9 for Windows and Android. 

Thank you so much.

I would switch to Kodi 19 or 20 today, but I maintain and share a super favourites list with my friends and family via mixplorer and gdrive to make sure they can get all the latest content and I have got them and myself completely dependent on it and other tools that I'm not smart enough to fix or find a workaround in Kodi 19 or 20.

**Comment by ErosVece** [comment]
First on Google gave me a repo where I could install SF on Kodi 20 :)
Updated on April 2022.

https://mrgsi.github.io/gsource/

**Comment by whatsuprob** [comment]
> First on Google gave me a repo where I could install SF on Kodi 20 :) Updated on April 2022.
> 
> https://mrgsi.github.io/gsource/

I appreciate your help. I've tried that version and I agree it's better than most other versions on Kodi 19 and 20. Jmoores version has improved immensely with the latest update from 2.25- v2.26 (I believe). Unfortunately, It did not work for most of the superfavs I have for tmdbhelper, youtube and other crucial 3rd party addons I use a lot for 1-click links and when I started decided to create all new links from scratch I ran into many links that did the infinite loop where you cannot exit out of the addon in the superfavorites link and go back to the main menu with all of your superfavs. It just keeps pushing you back into the addon even if you manually edit the links in super favorites (like switching to RunPlugin instead of ActivateWindow, which works for most of these in Kodi 18)  The only solution is to click the back button 4-5 times rapidly to purposefully crash the superfavs addon and then just delete the link and give up on that particular addon because its no longer a helpful shortcut, its hotel California lol.
The version you found is closest to my favorite version for 19 and 20 so far which is V 2.09 I believe, but like all the rest on Kodi 19 and 20 it's picky about youtube channel links, program addon links, system shortcut links, tmdb helper movies shows links, and other crucial 3rd party providers I like for sports.  And each time you update your tmdbhelper or switch to another version of tmbd either just when an update rolls through or because it no longer works reliably and you need to replace it with a different version from another repo. Just like you run the risk of having to find or create all new players in TMDB for it to work,  you also run the risk of all your superfav links no longer working in Kodi 19 and 20. This happened to me twice with tmdb and youtube before I gave up and slid back to Kodi 18 in defeat. I'm picking on youtube and tmdbhelper because those are the most popular, but it happens to me randomly with other addons too.

**Comment by ramjam720** [comment]
> Here, I installed Kodi 18.9 on Windows, and this works there: [24d0b16](https://github.com/dobbelina/repository.dobbelina/commit/24d0b163d679b2f1b9b72b5f0592f3ce4dbabc29)
> 
> In my opinion it's better to move to Kodi 20 :)

When I upgraded to KODI 19 (multiple times) many of my other addons stopped working.  I recently installed version 20 on my phone, and still many addons don't work.  Cumination works but many of the best sites (Perversija, PornHub, etc...) cease to work.  IDK why 1.77 is considered an upgrade.  It is very buggy.  It killed the users of KODI 18, and injured the users of 19 & 20.  I am not a dev, I don't understand code.  I only know what works for me, and what does not.  KODI 19 & 20 are not compatible for me because the developers of my old addons don't want to do the work to upgrade. 

Cumination 1.74 was pretty awesome, but 1.77 seems like a brick to me.  Maybe if there was another repo "Dobbelina 18" where those of us who are running the older KODI can find relief.  I am powerless to influence your actions, but I will ask that you consider doing this.  Thanks for your consideration.

**Comment by dobbelina** [comment]
Between kodi 18 & 19 and the upgrade from python 2 to version 3 there were many of my favorite addons that stopped to work.
Solution, install the newer kodi version as a portable, then you can jump between the old an new until addon developers catch on and upgrade their addons to be compatible with the latest version.
After a while you can ditch the old version, and when a new one comes out that might have issues, the cycle repeats itself.

**Comment by ramjam720** [comment]
_> Between kodi 18 & 19 and the upgrade from python 2 to version 3 there were many of my favorite addons that stopped to work. Solution, install the newer kodi version as a portable, then you can jump between the old and new until addon developers catch on and upgrade their addons to be compatible with the latest version. After a while you can ditch the old version, and when a new one comes out that might have issues, the cycle repeats itself._

Sounds like a nice idea, but I need to roll the clock back to the old version so that Cumination will work.  IDK how to write code (or alter it, or even find it).  I am relatively certain that there are literally thousands of KODI 18 users that are being impacted by this update.  I have personally set up around a dozen boxes for my friends here in Indonesia, and I know all of them are not working.

**Comment by ramjam720** [comment]
Thanks for the update.  Everything seems to be working, and bonus new sites too.  We appreciate all of your efforts.

**Comment by chrono111** [comment]
> Like I said, the next update will contain fixes so it works properly again.
> 
> If you need older versions, Kodi always puts addon zips in the packages folder in addons. So in %kodi userfolder%/addons/packages/ you will find older zip files that you can install (and turn of auto update until the next version).
> 
> That is, if you don't have some cleaner tool/service running that clears that folder.

For some reason I only see plugin video back to 1.1.75 zip in that folder. Do you have an ETA for 1.78 by chance? Thx!

**Comment by whatsuprob** [comment]
Thank you so much! I owe you a beer or coffee. Do you have a paypal etc.

**Comment by dobbelina** [comment]
1.78 released that should solve the issues, closing thread.
