### ISSUE TITLE
OSMC running Cumination no longer plays any videos and no play button showing

### ISSUE THREAD

**Issue by Budgie2** [dobbelina/repository.dobbelina#1071]
Running Kodi 20.1 on OSMC hardware.  Cumination (v1.1.78) has stopped working.  Strangely, the play option is not shown.  Videos are available and may be selected but not played.  Selecting a vid gives the line of the title etc but the only options are "Choose art" or Refresh and Refresh is greyed out.   Any ideas what has gone wrong and can I fix it?
Also some sites are no longer showing any content but not sure this is related.

**Comment by ErosVece** [comment]
That is weird.
It sounds like that when you click to play a video, it shows the Video Information dialog (the same you get with Kodi on Windows when pressing i)?
Because you talk about having 'Choose art' on screen.

Just saw this on https://kodi.wiki/view/Video_playback#Play
`The default option for the above keypresses can be modified to open the Information Page instead of play. `

I didn't know that, but it is indeed a setting.
Go to Kodi settings -> Media -> Videos -> Default select action. Set that at 'Play', the default setting.
Try to play a video now and see what it does.
Enable debug log, restart Kodi and try it again.
Also visit the sites with empty listings
 If you come across one, add that one to Kodi favorites or a Custom List. So we know in the log what site it was :)

Upload the debug log here. There is enough information to be found how to do it.

**Comment by Budgie2** [comment]
We learn something every day.  That sorted out my problem but I have no idea why setting had changed.  Must have been a glitch during update. 
On slightly different topic what has happened to SpeedPorn site?  Is it down or broken?

**Comment by Budgie2** [comment]
BTW Many thanks!!!

**Comment by ErosVece** [comment]
No idea, but it has been having problems for some time now, but the content on there is the same as on netflixporno (and a few other sites we don't have included because of the same content)

**Comment by Budgie2** [comment]
Noted and thanks.  Any suggestions for best sources for download resolutions.  They vary from full HD+ to unwatchable.

**Comment by ErosVece** [comment]
naughtyblog, seaporn have 1080 and 4k videos, but you'll need Real-debrid or something similar.
Porntrex has good 4k.

**Comment by Budgie2** [comment]
Hi and many thanks.  I see that my R-D account had expired so have renewed but am really stuck with getting it to work on your site.  Is there a how-to video or similar.  My version of Kodi has different look so am floundering here.

**Comment by Budgie2** [comment]
Got it now!
