### ISSUE TITLE
Please add the following sites 

### ISSUE THREAD

**Issue by desireyes** [dobbelina/repository.dobbelina#1078]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**If it's a site addition request, add url below**
Sites with no DMCA information will not be added

https://www.desihoes.com      (Indian Porn Videos)
https://www.porncaper.com   (Only good quality HD porn videos)
https://www.alluretube.com (High quality Classic porn movies)

Thanks my friend.
Desi Reyes

**Comment by desireyes** [comment]
DMCA pages:
https://www.desihoes.com/static/dmca
https://www.porncaper.com/dmca/
https://www.alluretube.com/static/dmca

**Comment by ErosVece** [comment]
Porncaper has 1 video added 2 days ago, and everything else is older than 6 months.
Do you think there will be more updates?

**Comment by desireyes** [comment]
Yes, Currently I am updating and if you please check, quite a few videos have been added in last couple of days.
Thanks

**Comment by ErosVece** [comment]
Ah, it's your site(s)?
Isn't there an api (or something) for the content on the sites? 😄

**Comment by desireyes** [comment]
:-( 
You got me there..
Yes, these are my sites. Two sites are running on adultvideoscript (https://www.adultvideoscript.com/) and one on KVS (https://www.kernel-video-sharing.com/en/)
I am not much of a programmer. Can you suggest the api or something to pull the content.
Really appreciate it.
Thanks

**Comment by desireyes** [comment]
Will google sitemap work?

**Comment by ErosVece** [comment]
Haha, I know KVS by name, because we made the decrypter for it 🤣 

But don't bother then, we can just scrape the pages like normal.

I'm just stunned that a webmaster is suggesting is own sites :)
Most webmasters and site owners don't like us, because they don't have ad revenue or other data when people use Cumination.

**Comment by desireyes** [comment]
I use kodi and your plugin in nice and just want to contribute to it.

**Comment by ErosVece** [comment]
This is Alluretube: https://github.com/dobbelina/repository.dobbelina/commit/fa15405fbc7a2c8a4352a1956f5d1e45b71db480

**Comment by dobbelina** [comment]
Seems resolved, closing issue.

**Comment by ErosVece** [comment]
@desireyes 
I promised you the last one, here it is: https://github.com/dobbelina/repository.dobbelina/commit/a5fa96b368a3f75bb0c8d294d6de8d01dc357d57

Can you look up in the site files what the block_id is for search ajax?
Something like `list_videos_videos_list_search_result` or  `list_videos_common_videos_list`?

I can't check it myself, because I couldn't find a search keyword that provided enough links for multiple pages 🤣

**Comment by desireyes** [comment]
Hi
Is there a way to send you a private message? Server is running into issues with heavy load. :(

**Comment by ErosVece** [comment]
Because of Cumination?
Send me a mail at my name @protonmail.com

**Comment by ErosVece** [comment]
> Hi Is there a way to send you a private message? Server is running into issues with heavy load. :(

I have send you a message with alluretube contact form :)

**Comment by desireyes** [comment]
Hello Friend. 
I don't think my alluretube.com contact form is working. Can't find your email. Can you please send one to desisites@hotmail.com
Please. Real problematic issues with the server.
Really appreciate it.
Thanks
Desi
