### ISSUE TITLE
Allure Tube and EroGarga down

### ISSUE THREAD

**Issue by afront66** [dobbelina/repository.dobbelina#1191]
I did not see these 2 sites mentioned in open tickets.  Allure Tube says "Could find supported link."  Thank you for your attention.

**Comment by afront66** [comment]
In the log file for EroGarga, I see 2 main errors: 1) error <general>: Open-error probing input format; 2) OpenDemuxStream-Error creating demuxer.  Hard to attach file bc can't get it from fire stick.

**Comment by dobbelina** [comment]
I can confirm the issue on these 2 sites on my windows rig.

**Comment by ErosVece** [comment]
I can confirm that Erogarga is fixed in the next update, or add it yourself from here: https://github.com/dobbelina/repository.dobbelina/commit/447cfc837d6551f895331a01406c724ada58d0f4
I also added Lookup info to the context menu.

Alluretube, they encrypted the videolinks. Maybe someone smarter then me (or more sober) can figure it out? 🤣

**Comment by ErosVece** [comment]
Forget what I said about Allure Tube 😉 
It's fixed: https://github.com/dobbelina/repository.dobbelina/commit/c5c0ce924427ff1f3803a2424f4c3448371fb5de

**Comment by afront66** [comment]
Nice work.  Thank you.
