### ISSUE TITLE
https://fullporner.com/ and https://www.xfreehd.com/

### ISSUE THREAD

**Issue by Akkari1988** [dobbelina/repository.dobbelina#1192]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

https://fullporner.com needs an update. Many videos are displayed there even though they are no longer on the website which many videos do not work,
https://www.xfreehd.com/ Categories doesn't work, no videos are displayed

### Kodi version

20.2

### Cumination version

1.1.88

### Operating System and version

android and windows

**Comment by ErosVece** [comment]
Xfreehd categories will be fixed in the next update, or copy the updated file yourself: https://github.com/dobbelina/repository.dobbelina/commit/6bd164f177e0ad9ef65e0810431571a8b3b592c9

About Fullporner.
Cumination is using `fullporner.org`, and not `fullporner.com`.
Same logo, same name, but the content is not the same.
A lot of videos are the same, but there are also some differences.
For example, the `.com` site has 5x the same Andi James video (from My Pervy Family), where `.org` has only one.
Or, the `.org` site has the video `Don’t Touch My Drumset – Mayara Lopes`, that isn't on `.com`.

What you'd see on the `.org` site, the same exact content is in Cumination.
I tested from the first page a few videos, and from page 6. And every video played fine.

For the next time, when you say 'many videos do not work', please give titles or links of videos that don't work.

**Comment by Akkari1988** [comment]
this video dosnt work , https://fullporner.org/watch/58962/

**Comment by Akkari1988** [comment]
then change the website from .org to .com if .com has more videos :)

**Comment by ErosVece** [comment]
> this video dosnt work , https://fullporner.org/watch/58962/

Euhm, yes....that doesn't play in Cumination because the video is removed.

Cumination is like a browser, a way to visit all kinds of adult sites.
So we don't control, own, update or have anything to do with the websites that you can visit with Cumination.

> then change the website from .org to .com if .com has more videos :)

Yeah, no, for starters, the `.com` site doesn't have any DMCA information.
But you are free to create your own custom site for it.

**Comment by Akkari1988** [comment]
I don't know how to do it, I've tried many times but it doesn't work, but you can make the page and send it to me privately 😁
