### ISSUE TITLE
Newly added Hotpornfile error

### ISSUE THREAD

**Issue by dobbelina** [dobbelina/repository.dobbelina#122]
Newly added Hotpornfile unfortunately don't wanna play along?

**Comment by 12asdfg12** [comment]
The addon is ok but the website sucks. The latest videos don't have a link for streaming. Download links are available but we can't use this because the files are archived. Older videos works but the host (gounlimited) is not great.

Justporn.to is not working because, since openload gone, there is no working links on the website.

Also xvideohits use openload, it doesn't work either.

**Comment by SomeDood** [comment]
Yea, I noticed this days ago. It used to have the actual videos on the page, and they've removed them again for some reason. Thanks for attempting it tho.

**Comment by dobbelina** [comment]
Might as well keep the openload hosters for a while, maybe they update their links
later on.
