### ISSUE TITLE
Javguru not working on Windows

### ISSUE THREAD

**Issue by steph09** [dobbelina/repository.dobbelina#1286]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

Hi, Don't think this is necessarily a bug but I wasn't sure where else to ask about this.

On my Windows PC JavGuru will not work, It requires a cloudflare check and upon using flaresolverr to pass that it seems to loop a few times & then not play. It happens on both Kodi version 20.4 as well as the latest 21 Beta 2.

However on the Chromecast with google TV downstairs it works fine without even doing a cloudflare check. I also noticed that it brings up extra sources that never used to come up on the Kodi PC build upstairs.

Just wondering why it's different between Windows & CCWGTV and if it's something that can be resolved on Windows.

Thanks.

### Kodi version

21 Beta 2

### Cumination version

v.1.1.100

### Operating System and version

Windows 10

### URL to debug log file

https://paste.kodi.tv/bewitididi.kodi

**Comment by Gujal00** [comment]
This is due to ssl compatibility with cloudflare.
Kodi on Windows is stuck on Pyrhon 3.8 and doesnt support all ssl schemes and gers a CF block
Kodi on Android is bundled with Python 3.11 which is lot modern and supports newer ssl schemes and works fine with sites behind CF

Even the upcoming Kodi 21 Omega only bundles Python 3.8 in the Windows version so cant be done anything about it.
