### ISSUE TITLE
Icons not displaying properly

### ISSUE THREAD

**Issue by flhthemi** [dobbelina/repository.dobbelina#131]
I don't know if this is a problem with UWC and views or with the skin I use (Aeon Nox Silvo V7.0.8) but when I got an update to the skin to 7.0.8 is when it seems to have started. But I know very little about coding and just thought I would mention it here so you can check it out if you want.

Seems it's being stretched as this actually should just display the banner at the bottom in list mode. :)

![screenshot000](https://user-images.githubusercontent.com/8205131/69427752-db13f980-0cfd-11ea-9f84-9515fc13d235.png)

BTW, thanks for maintaining this addon, You've been doing a great job!

**Comment by dobbelina** [comment]
Must be a skin issue.
If you got an update recently, i'd suggest you direct the issue to the skin developer.

**Comment by flhthemi** [comment]
OK I thought that since this was the only app having the issue it might be the app's bug.

Thanks!

**Comment by DJMix-I-Can** [comment]
It's a aspect-ratio issue with the view type of list on your skin. Is that the No Limits Build? or just using the Aeon Nox Silvo skin?
Anyway, I'm playing with that build & I have the view set to list. The aspect ratio is set to "stretch". https://imgur.com/ch3Cok4
If you change it to "keep" it would fix the stretching & then it would lower the icon.  https://imgur.com/gNAa1cT and then the directories would look like this https://imgur.com/Uxx6Dxs Notice the borders are no longer aligned to the images.
Your best bet would be to change a word in the UWC addon if your issue is just with this addon. It would still look like the first image of the icon being lowered & the other directories but now the border is aligned with the images & it won't affect the list view of the other addons, just UWC.  https://imgur.com/bxFW10d & https://imgur.com/t4neaW9
I personally do this every time UWC gets updated because under movies, I don't get the view type of square wall. I change it to addons. The file to modify would be default.py in the UWC addon and the line you would modify is line 34, "xbmcplugin.setContent(utils.addon_handle, 'movies')" change movies to addons, save, reload the skin or close Kodi and reopen. In order to see the changes.

**Comment by flhthemi** [comment]
> I personally do this every time UWC gets updated because under movies, I don't get the view type of square wall. I change it to addons. The file to modify would be default.py in the UWC addon and the line you would modify is line 34, "xbmcplugin.setContent(utils.addon_handle, 'movies')" change movies to addons, save, reload the skin or close Kodi and reopen. In order to see the changes.

Thanks for this it worked like a charm!!! :)

**Comment by DJMix-I-Can** [comment]
Your welcome, just keep in mind. Every time you update the addon, it will revert back to movies & you'll have to change it again.
