### ISSUE TITLE
Sxy Prn duplicated in favorites and with wrong number

### ISSUE THREAD

**Issue by xXSkizzo89Xx** [dobbelina/repository.dobbelina#1332]
### Prerequisites

- [X] I have searched the issue tracker to avoid opening a duplicate issue.
- [X] I have read the [documentation](https://github.com/dobbelina/repository.dobbelina/wiki/Cumination:-Debug-Logging-and-Uploading) on how to create a debug log file.

### Description

After the recent fixes to the favorites Sxy Prn appears several times and with the wrong number

Sort by: site & name, in folders

![screenshot00000](https://github.com/dobbelina/repository.dobbelina/assets/141495940/80de6b1f-17b8-4123-a376-55d10c6b9d70)

### Kodi version

20.5 and 21

### Cumination version

v.1.1.105

### Operating System and version

Android and Windows 11

**Comment by DJMix-I-Can** [comment]
What's up @dobbelina Hope all is well....So I just tested this favorites fix. I applied it on Android Kodi Nexus & Omega. When I select "Favorite videos", I get a "No Favorites Found" notification. I know my favorites is still there because it's in the userdata folder. Once I revert back to the old favorites.py, my favorites shows up again. I also tested it on a Windows installation & it worked fine. I didn't receive the notification like on the android. All of my favorites showed up. It's an Android issue. I thought I'd mention this now before you push it out on the next update. A lot of people well be pissed off when they notice that their favorites has disappeared.
