### ISSUE TITLE
Where is 12asdfg12

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#136]
Hi, what happened to him? Suddenly seems to be non existent. Has he left GitHub. If it is, it would be a great loss to our UWC community. 12asdfg12, if you can read this, we would request you to come back.

**Comment by dobbelina** [comment]
I can not find his account,, it's a "404"?
Don't know the reason for this.
But if it's because he/she deleted it i can respect that.
UWC owe he/she a great debt of gratitude for all the contributions made.
### BIG Thank you and all the best to you 12asdfg12!
Let's hope someone else can step up to the plate and continue the amazing
work that 12asdfg12 did.
12asdfg12, we are missing you already ❤️

**Comment by imurreflection** [comment]
Hey Dobbelina, he is back..looks like some error on Twitter's part. Welcome back 12asdfg12.. We all needs you.

**Comment by 12asdfg12** [comment]
My account was "flagged" (I have no idea wtf that means) and that's why my profile was hidden. now the account is unflagged :D

**Comment by imurreflection** [comment]
Hey mate, extremely happy to see you back. Actually, people i follow become 5 instead of 6 so i realized you are missing. Welcome back !!!

**Comment by dobbelina** [comment]
What a relief!
For a moment there I thought you were gone 😄

**Comment by imurreflection** [comment]
Since, the gentleman is back, i am closing the issue.
