### ISSUE TITLE
streamxxx.tv not working

### ISSUE THREAD

**Issue by luckonwheels** [dobbelina/repository.dobbelina#138]
Doesn't show any videos

**Comment by dobbelina** [comment]
Issue confirmed

**Comment by 12asdfg12** [comment]
fixed + added multiple hosts.
he best host (mixdrop.co) requires a small fix in resolveurl to work:

in mixdrop.py file (from resolveurl plugin, not UWC) change line 36 from:
`            r = re.search('vsrc="([^"]+)', r.replace('\\', ''))`
to 
`            r = re.search('vsrc?="([^"]+)', r.replace('\\', ''))`

or just wait until will be fixed in resolveurl

**Comment by dobbelina** [comment]
fixed by 12asdfg12 #144
Thanks!
