### ISSUE TITLE
DaftSex - vk link could not be resolved

### ISSUE THREAD

**Issue by s4ik0s4n** [dobbelina/repository.dobbelina#152]
Some videos play on the DaftSex site, found in the Whitecream Scenes section, but most try searching for the videos from other sources (I assume) then display the error 'vk link could not be resolved' if it can't find them.

**Comment by 12asdfg12** [comment]
Can you give an example?

**Comment by DJMix-I-Can** [comment]
I couldn't replicate it. I tried numerous videos in categories, search and random TV, they all worked. Looked at the debug file and never saw it trying to stream from VK.com. They all scraped from their servers, crazycloud & daxab.

**Comment by s4ik0s4n** [comment]
Sorry, just woke up. I've got 2 videos for examples I just found. The titles are "The Virgins Revenge ~Sex Beyond The Grave!~ (Motion Comic Version)" and "The Unfaithful Life Of A Newly Married Women - The Motion Anime". The were some more yesterday, but I've slept since then. They play just fine in my phones browser, but not on my android box's Kodi. Do you want links to the webpages?

**Comment by DJMix-I-Can** [comment]
Ok, you're right. The link for The Virgins Revenge sex is //psv51-1.daxab.com/videos/-127285837/456239337/360.mp4?extra=EhyRo8M9Vx8iELuudW8xGw  The daftsex.py files doesn't have server 51-1 in there that's why it wouldn't play. If you know how to modify the py file, you would need to go to line 36 and add the server number '51-1', to it. It should work after.
As for the other video, there are two versions. One is 11 months old and the other one is a year old, they both work fine. The servers they're on are on the list.

**Comment by DJMix-I-Can** [comment]
Ok, I'm going to have to add to this. When I tested it, it was on a Windows laptop and a fresh install. The VK links didn't work because I didn't have Real Debrid authorized in the ResolveURL.  I didn't think about authorizing the ResolveURL on the laptop. When I tested it again on my Nvidia Shield which doesn't have that added server of 51-1, it scrolled past the crazycloud & daxab servers and onto the VK link. Since Real-Debrid is authorized on the shields ResolveURL account, that VK link was passed off to them (premium) and was able to stream it. To test, I removed the added server from the daftsex.py file on the laptop, tried to stream it again but with RD authorized in the ResolveURL. It passed through the crazycloud and daxab servers and onto VK. I didn't get the error this time, it played. I'm guessing you don't have a premium service of Real-Debrid or Premiumize?

**Comment by s4ik0s4n** [comment]
I do not. I'll consider investing in it though.

**Comment by DJMix-I-Can** [comment]
Try to take advantage of this, this was just posted. To test out the premium service.
https://www.reddit.com/r/Addons4Kodi/comments/ejkbhw/premiumize_christmasnew_years_7_day_free_trial/

**Comment by 12asdfg12** [comment]
The next version no longer requires server searching, but in some cases the video is not hosted on daxab or craycloud servers, in which case ResolveURL is used for playback from the vk.com link and a premium account is required but this is quite rare.

**Comment by DJMix-I-Can** [comment]
Thanks @12asdfg12

**Comment by dobbelina** [comment]
Issue resolved in v1.2.8
