### ISSUE TITLE
Thumbnails

### ISSUE THREAD

**Issue by lance77tour** [dobbelina/repository.dobbelina#205]
What's with providers not having thumbnails only the camera?

Why are there still providers who've not worked for ages? I've had to make a list to know which ones to turn off or remove from code.

**Comment by dobbelina** [comment]
Hi lance77tour,

Please name those providers that you find not working.

**Comment by DJMix-I-Can** [comment]
I'm currently going through each section to see what's working and what's not working. All of the providers have thumbnails. If the directory of that site doesn't load, I don't get anything, not even the camera icon you're describing. Are you sure you're up to date? Did you check your log file to see if you're getting errors?

**Comment by lance77tour** [comment]
Thanks for getting back to me. RD and Premiumize are paired, all cache has been cleaned. Here are the ones that aren’t working:

MOVIES
Xtheatre              every movie unable to find supported link
PornHive             Select link the circle spins upper right corner of screen has the PLAY symbol and then it all goes away, for each available link
FreeOMovie      Select link the circle spins upper right corner of screen has the PLAY symbol and then it all goes away, for each available link
SpeedPorn         Shows Cat/Tags/Search/NxtPg no content
MangoPorn        Select link the circle spins upper right corner of screen has the PLAY symbol and then it all goes away, for each available link

SCENES

PornDoe              Shows Cat/Tags/Search/NxtPg no content
XVideoHits          Shows Cat/Tags/Search/NxtPg no content
YesPornPlease  Shows Cat/Tags/Search/NxtPg no content
Xtasie                    Shows Cat/Tags/Search/NxtPg no content

TUBES

PornDigPro         Cat/Pg no ontent
PornDigAmat     Cat/Pg no ontent

**Comment by DJMix-I-Can** [comment]
Ok, I just finished checking. Using UWC 1.2.14 Under settings, General Daftsex resolver, set to ResolveURL. Using ResolveURL 5.0.38 & use Real Debrid. Some issues could be ResolveURL issues for example, Mangoporn works for me if I just use Rapidgator as server.
These are my results.
**Scenes**
sxyporn, top rated last week & orgasmic doesn't load directory.
watchxxxfree, directory doesn't load
woxtube, entering categories directory doesn't load, search doesn't work.
XTasie, doesn't load directories.
Pornsland, has a new site. **(Has been acknowledged as not working)**
Porndoe, directory doesn't load.
xvideohits directory doesn't load.
yespornplease, website doing maintenance but might have changed it to yespornplease.name, changing the url on the code doesn't help.**(Has been acknowledged as not working)**
Freepornstreams, links are for ubiqfile.**(Has been acknowledged as not working due to ResolveURL)**
Hotpornfile, videos don't play.

**Tubes**
Anybunny videos don't play.
Porndig Amateur & Professional doesn't load directory.
Amateur Cool, no next page.
VPorn Categories directory doesn't load.

**Hentai**
HentaiHeven videos don't play.

 **Movies**
Xtheatre, videos dont play.
Pornhive, hit or miss, depends on the hoster used. **(Probably ResolveURL issue for videobin hoster? since it gets passed to ResolveURL.)**
StreamXXX, tags, international movies, search overall, search scenes doesn't appear on the main page.
Eroticage, no next page.
SpeedPorn, no directories.
Mangoporn, next page doesn't load thumbnails. Categories doesn't load directory.

**Comment by lance77tour** [comment]
Thanks for the information. I’ll did into it a bit later.

Keith

**Comment by DJMix-I-Can** [comment]
My apologies for the second notification. I wound up deleting the original post because I realized that I wasn't finished checking the scenes section from yesterday. I believe I'm done now. I wasn't originally going to post all of this at once but since it was brought up, thought I'd chime in on it.
k, I just finished checking. Using UWC 1.2.14, In settings, General, Daftsex resolver, it's set to ResolveURL. Using ResolveURL 5.0.38 & use Real Debrid. Some issues could be ResolveURL issues for example, Mangoporn works for me if I just use Rapidgator as server.

**Scenes**
sxyporn, top rated last week & orgasmic doesn't load directory.
watchxxxfree, directory doesn't load
woxtube, entering categories directory doesn't load, search doesn't work.
XTasie, doesn't load directories.
Pornsland, has a new site. **(Has been acknowledged as not working)**
Porndoe, directory doesn't load.
xvideohits directory doesn't load.
yespornplease, **website doing maintenance but might have changed it to yespornplease.name, changing the url on the code doesn't help.(Has been acknowledged as not working)**
Freepornstreams, links are for ubiqfile. **(Has been acknowledged as not working due to ResolveURL)**
XXXStreams, links are for ubiqfile.**(Has been acknowledged as not working due to ResolveURL)**
Hotpornfile, videos don't play.
XTasie doesn't load directory in main, categories, top rated or most viewed. Search doesn't load either.
XVideosSpanish, Videos don't play.


**Tubes**
Anybunny videos don't play.
Porndig Amateur & Professional doesn't load directory.
Amateur Cool, no next page.
VPorn Categories directory doesn't load.

**Hentai**
HentaiHeven videos don't play.

**Movies**
Xtheatre, videos dont play.
Pornhive, hit or miss, depends on the hoster used. **(Probably ResolveURL issue for videobin hoster? since it gets passed to ResolveURL.)**
StreamXXX, tags, international movies, search overall, search scenes doesn't appear on the main page.
Eroticage, no next page.
SpeedPorn, no directories.
Mangoporn, next page doesn't load thumbnails. Categories doesn't load directory.

**Comment by dobbelina** [comment]
Thanks for reporting.
That's a fair amount of issues there.
Let's hope our devoted programmers can find time to resolve some
of those mentioned above.
Remember, everyone helping out here is doing it on their free time,
without getting paid.so we have to be very thankful whenever they give
a helping hand.
Special big thanks to 12asdfg12 & jdoedev123. :thumbsup:

**Comment by DJMix-I-Can** [comment]
I agree bud, that's the reason why I didn't mention anything. I personally don't use those site & haven't seen any mentions about them, so thought they weren't being used as much. If there's anything I could fix or notice that it's working again, I'll remove it from the list. For example, sxyporn is now working again. BTW Datoporn is showing as broken but I just checked it again and it's working again, can you double check. Thanks to all..

**Comment by lance77tour** [comment]
Thanks again for your hard work. I have a question. You know when searching or opening up the site there are videos that are 30 sec, 1.5 min, 4 min, etc. is there code I could add into the current code that would only ever show a specific time/length of video. Like >10min or …..

Thought I had the other night.

**Comment by DJMix-I-Can** [comment]
@lance77tour I'm trying to learn Python so can't really help on that. Did notice that feature with XHamster. Might want to look at that code.

**Comment by lance77tour** [comment]
Yeah, I’m learning about code as well. Super cool that we can see the code being used and trying to understand what it’s saying and not making changes unless you know what it is and if it affects other code in other files.

**Comment by 12asdfg12** [comment]
mangoporn - fixed categories
speedporn - fixed + added actors & genres
xvideoshits - the videos are now hosted on netu.tv which is not supported
HentaiHeven - videos don't play on the website
eroticage - nextpage fixed

**Comment by DJMix-I-Can** [comment]
> 
> 
> mangoporn - fixed categories
> speedporn - fixed + added actors & genres
> xvideoshits - the videos are now hosted on netu.tv which is not supported
> HentaiHeven - videos don't play on the website
> eroticage - nextpage fixed

Thanks....

**Comment by lance77tour** [comment]
😎

Thanks
Keith
________________________________

**Comment by 12asdfg12** [comment]
> Anybunny videos don't play.

fixed
> Porndig Amateur & Professional doesn't load directory.

fixed
> Amateur Cool, next page doesn't work after page 2.

added search. i forgot to check the problem with the next page so it's not fixed
> VPorn Categories directory doesn't load.

category fixed
+
> StreamXXX, tags, international movies, search overall, search scenes doesn't appear on the main page.

these options are available on streamxxx from scenes

pornhive - some external hosts are bad, we can't do anything in UWC to fix this, the addon is ok

Xtheatre - using netu.tv, not supported

**Comment by lance77tour** [comment]
You’re a MACHINE 😊

**Comment by 12asdfg12** [comment]
Amateur Cool - next page fixed
Xtasie - there are no videos on the web page, just a collection of gifs, it should be removed from uwc

the host netu.tv (waaw, hqq) is fixed on resolveurl github.

**Comment by DJMix-I-Can** [comment]
Thanks @12asdfg12 , Everyone be safe out there...

**Comment by lance77tour** [comment]
Hi,

Before I deleted the log, I wanted to share with you the errors from Wednesday. I’ve noticed there are a lot of thumbnails showing the camera and some thumbnails having the “play symbol” on them that I think is cool.

**Comment by lance77tour** [comment]
Hello, is UWC down? I’ve received installation failed after trying to reinstall.

**Comment by lance77tour** [comment]
Hi,

Has anyone noted issues with UWC? Some scenes/movies/tubes links continue to play the same video “PurgatoryX with Richelle Ryan with a Tow Truck Guy.
