### ISSUE TITLE
No Thumbnails

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#244]
Many sites are not showing thumbnails. I m checking all sites now but so far, following sites have no Thumbnails:

Porn00
ViralVideosPorno
Mr Sexe
Ipornovideos

Kindly check

**Comment by jdoedev123** [comment]
I have Thumbnails for all of the sites mentioned above.
Not sure what your problem is. I don't know if it is related but I just fixed a problem of an expired Certificate ( AddTrust_External_Root ) which has been breaking many things on the Internet since it expired May 30, 2020. For me it broke HQPorner, but I did not check all the other sites. Some of my computers updated themselves to the fix the problem while others needed to be manually fixed.

**Comment by imurreflection** [comment]
Thank you mate. All other sites in "scenes" doesn't have this. May I know how can I fix the certificate on my android TV box. Also, please note that I m on VPN as these sites are blocked here.

**Comment by imurreflection** [comment]
I found this is an issue with VPN. Without VPN apart from.porn00 all sites are showing thumbnails.  Sorry for the trouble. Closing the issue now.
