### ISSUE TITLE
How come it takes so long to load/view my WC favorites?

### ISSUE THREAD

**Issue by frankee123** [dobbelina/repository.dobbelina#262]
I hate to ask this, but I like to back out and go back in to my whitecream favorites to refresh the camgirl images. I've noticed for maybe past few months or so the blue circle just will spin the middle of the screen for like 30-45 seconds when it used to be much faster. I know it isn't a issue with my speed or my android box, it's simply going into my whitecream favorites which seems like it takes too long. Does anybody else have the same issue or know what to do to get it back faster please? TY

**Comment by DJMix-I-Can** [comment]
First, you stated it's being going of for months, that is a big window!!! I have almost 300 favorites & they all load very fast. I'm using the 2015 & 2019 Shield. I usually only save Chaturbate cammers to my favorites, anything else I save via SuperFavorites via my USB stick. Have you been saving everything you like from different sites into my favorites? If so, that could be an issue. Numerous sites have changed or died. When you go into your favorites, it's looking for the metadata of those shortcuts. If you have favorites from sites that have died or their code has changed, it' will try to get the metadata (info, link) until it times out. That takes time, which will make you see the "blue circle" going around & around.

**Comment by frankee123** [comment]
ty that makes sense. I have scenes favorited as well which must be the issue.ty sir

**Comment by frankee123** [comment]
hmm , so I downloaded all the scenes that would except for like 4 scenes. It still takes long. Must be my android box I guess? No idea. Ty though for the idea!

**Comment by DJMix-I-Can** [comment]
How much stuff do you have? You could try enabling debug and looking at the log file. See if there's a bottle neck somewhere.

**Comment by frankee123** [comment]
I have 224 favorites but only am down to 6 scenes that wouldn't download for some reason. the rest are all camgirls. Sorry, how do I enable debug sir?

**Comment by DJMix-I-Can** [comment]
Instructions are [here.](https://kodi.wiki/view/Settings/System/Logging#Debug)
Another thing you could try is creating a back up of your favorites file and create a new one. You mentioned you're on an android device. Close your Kodi or back out of the UWC addon. The path for UWC favorite is Android/data/org.xbmc.kodi/files/.kodi/userdata/addon_data/plugin.video.uwc
In that folder you should see a favorites.db file. This is where your favorites are stored & .db is short for database.
Rename that file favorites.db to favorites.dbBAK. Reopen Kodi if you closed it or go back into UWC if you didn't. Double check and see if your favorites is now empty. Start adding favorites in there. Once you think you've added enough, recheck to see if it's still slow. If it is, it's your device or your Kodi setup. Another thing to consider is if you're maintaining your Kodi setup. For example... There are users who download different addons to try out and then remove it. They're constantly doing that but don't clean out the remnants of that add-on called orphans. They also have dead repositories in their setup. They're using a build, that has a lot of unnecessary stuff. The thumbnails folder is full of images that has been saved since you first started using Kodi... That folder alone, could go up to a gig or more. It could be anything. I could go on but you get the idea. 
You could also try a cleaner to clear out old thumbnails, packages, cache etc.etc.. See if that helps out. 
I really don't know you're setup. I only know it's an "Android box" Good luck..

**Comment by frankee123** [comment]
Ty so much for the help and ideas. I barely have anything on the android box besides kodi. I do use indigo and know about clearing the cache, packages, and images but ty for that! I really don't know what the issue is. I don't know if I can catch like all 200 girls i have saved to be online at once, to try making a new favorites folder lol. I'll keep trying dif things. Ty

**Comment by DJMix-I-Can** [comment]
Out of curiosity, did you just install Indigo or did the problem start occuring after you installed Indigo? I know you mentioned it's been months but Indigo is usually frowned upon. Personally, I wouldn't install Indigo. A cleaner I use is part of a program add on called the reaper wizard. Be careful with it though, if you don't know what you're doing you could reset your Kodi installation.

**Comment by DJMix-I-Can** [comment]
BTW I didn't expect you to re-add the favorites one by one. Just favorite anything in order to build the database and see if your favorites data base is the culprit or not.

**Comment by frankee123** [comment]
Oh no worries sir, I gotcha. I've had indigo for a while. My favorites did work fine with me having it. Should I try uninstalling it and seeing what happens? This is also just a guess, but do you think with the myfreecams not working, that maybe it's a possible reason? I don't have that many myfreecam girls saved, but maybe I have like 20 or so in my favorites. I know it isn't working atm, could that be a reason why you think? Ty

**Comment by DJMix-I-Can** [comment]
Myfreecams grabs the metadata fine, it just doesn't play. That shouldn't be the problem. You could try uninstalling it and see what happens, as long as you you know where to get it from if you want to reinstall.

**Comment by frankee123** [comment]
I was looking into the reaper wizard add on but it looks like it does a fresh install of kodi as in clean wipe? Is there anyway to keep WC addon and all my favs etc and install it do yo know?

**Comment by DJMix-I-Can** [comment]
It doesn't do an automatic wipe. I'm just giving you a heads up that there's an option for that. Honestly, if you're not comfortable messing with it, then don't.

**Comment by frankee123** [comment]
Ok thanks so much.

**Comment by frankee123** [comment]
So I uninstalled indigo and that didn't change anything. I also noticed that the blue circle in the middle takes a while if I remove something from my favorites as well. I'm wondering if I need to uninstall then reinstall whitecream maybe?

**Comment by imurreflection** [comment]
@frankee123 Hi, for backing up your favorites and UWC keywords , you can use Ares wizard. This will help you restore the entire settings and add-ons including username and passwords as it is. However, it's not compatible with kodi 18 but there is a work-around for this but works only on UWC favorites and keywords. First, you need to take backup for UWC keywords and favorites preferably on usb ( Though, you can save on internal drive also), then uninstall Kodi completely. Find Kodi 17.6 build available easily on internet, install it. Make sure you turn off the automatic update feature off for your android device and once installed, for Kodi too. Once 17.6 is installed completely, restore your favorites and keywords from UWC settings and once you confirm everything, head to google playstore and update kodi to latest version. Ares wizard will not work now but you don't need it anyways. Make sure you take the initial back-up on USB or move the favorite and keywords file in internal folder like "Download."  If there is any confusion, write here.

**Comment by frankee123** [comment]
Ty so much. It seems like a bit of a hassle so I think I'm just going to deal with my issues.
