### ISSUE TITLE
Site addition request

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#299]
Hi..This is a special request to our developers DJMix-I-Can and @jdoedev123 if they can add desixnxx2.net. This is the only site which provides regular update on indian content both in SD and HD. I hope, you will consider this Request

**Comment by imurreflection** [comment]
Hi @DjMix-I-Can & @jdoedev123 friends. If the addition is not possible,please advise and I will close this request.

**Comment by DJMix-I-Can** [comment]
Personally, I won't be able to do it. I'm not a dev, I'm still a grasshopper. I took the initiative to start learning python in order to understand how the add-ons work in Kodi. I'm still learning & have a long way to go. If I recall, this was asked a couple of months back & it was decided that it wasn't worth it. 
Sorry..

**Comment by imurreflection** [comment]
It was decided by 12asdfg12 and not by community. He said anyone else can add it but he will not. Anyways, closing the issue now. Thanks
