### ISSUE TITLE
ffmpeg for Fire TV?

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#361]
Absolutely love the new cam download feature.  It works great on Windows.  I was wondering if it's possible to use this on a Fire TV (Firestick) device?  Thanks.

**Comment by jdoedev123** [comment]
It is technically possible to port ffmpeg to Android. I have done it but don't recommend it for the faint of heart.
I am working on what I believe is a move practical solution for devices such as Fire TV by adding a "Remote Video Download"  to UWC  which would allow download on another device/PC/server on the same local network.

**Comment by TarkusLV** [comment]
Oh, I like the sound of that!

There are actually ffmpeg apps in the Play Store, but I'm guessing they wouldn't work for our purposes, and are meant for conversions from within the app.  Your idea for remote download would indeed be better anyway.

**Comment by surreydave** [comment]
Could FFmpeg be downloaded from a repository, like dobbelina for example so that it can be available within Kodi?
This has been done before, it was part of the Super Repository (SR) designed for Kodi 17 (not 18), this does not work now as it requires a dependency (os.Openelect.tv v4) that is no longer available.

**Comment by Gujal00** [comment]
@dobbelina this issue can be closed
