### ISSUE TITLE
how to download from webcams with ffmepg in ubuntu?

### ISSUE THREAD

**Issue by joselbcn36** [dobbelina/repository.dobbelina#364]
Hi there, 

No that there is an option to download from webcams I would like to try out.

I use ubuntu 20.04 and for use this new option, I have downloaded the ffmepg tools from libreelec, unzip and just edit the addon.xml and delete the request line as it is necessary openelec version 9.00.
Then I have compressed as zip format again and was able to install as addon for kodi.

After that I have configured the path for ffmepg as : /home/myhomedirectory/.kodi/addons/tools-ffmepg.tools/bin.

Open webcams, go to chaturbate webcams, focused in one webcam, right click or context menu, download video, play video ...... but it displays error and ckeck for registry.

Can you point me what I am doing wrong?

**Comment by jdoedev123** [comment]
I use a variant of Ubuntu 20.04 (Pop OS) and have also had problems but have not really tried to diagnose the problem as I use another method to download Webcams.
In my case, I have a number of ffmpeg versions but still have problems with the latest addition to UWC especially with the ffmpeg directory permissions causing problems.
Again I have not gone deep into fixing the problem as I use streamlink instead of ffmpeg to download Webcams outside of UWC.

To use this method on Ubuntu et.al.:
1) Install Streamlink: sudo apt install streamlink
2) Get latest Webcam plugins from:
[Streamlink-Plugins](https://github.com/Damianonymous/streamlink-plugins)
3) Sideload Webcam plugins:
Set the XDG_CONFIG_HOME variable of where the plugins are
$XDG_CONFIG_HOME/streamlink/plugins
For example if plugins in /opt/streamlink/plugins
export XDG_CONFIG_HOME=/opt
This can be added to .profile file to always add to Environment.
4) Download Webcam stream:
For Example:
streamlink https://chaturbate.com/christina_joness best -o Chaturbate.20.11.09.Christina_Joness.XXX.720p.mp4 >/dev/null 2>&1 &

I am working on automating this as a UWC feature. Possibly as part of a "Remote Download Video" feature that could be in background on the same computer or any device/PC/Server on local network.

**Comment by jdoedev123** [comment]
Finally did  a deep dive of Ubuntu problem with stream download. 
1) Their are bugs for Linux in the download code. 
For Linux     proc = subprocess.Popen(cmd, shell=True, startupinfo=info)
not     proc = subprocess.Popen(cmd, shell=False, startupinfo=info)
as in the present utils.py code.
2) It is sensitive to where the ffmpeg binary is. It does not like "Location of ffmpeg" being in a normal system directory such as /bin which is common on most Linux's. The "Location of ffmpeg" directory needs to have write permission for the user.
3) It is sensitive to where the output file is on the network. ffmpeg does not like the Download Directory directly on an NFS connection. But it is ok with an NFS drive mounted to the local filesystem.
