### ISSUE TITLE
Truncated cam stream downloads

### ISSUE THREAD

**Issue by TarkusLV** [dobbelina/repository.dobbelina#366]
I've found that almost all of my cam downloads are not closed properly (truncated), creating issues in some players, including Kodi.  Kodi will play them, but doesn't know the length and you cannot seek in them.  I can fix them in HandBrake (such as converting to H.265), but that's a slow process.  Even HandBrake has an issue with them, immediately jumping to 100% in the first pass, though it continues to process and convert the file.

Some files close properly, but it's like maybe 10%.  The vast majority are truncated.  This is using Windows.

**Comment by jdoedev123** [comment]
This is a known issue with recording live streams with ffmpeg or streamlink due to not all the header info being available at the beginning of a live stream. I normally run the files back threw ffmpeg which can be completed quicker than HandBrake.
I have seen different takes on what parameters to use for ffmpeg for the conversion.
The automated stream capture and convert program chaturbate-node used the following to convert a captured stream: 
for ".ts" sources:
ffmpeg -i inputfile -y -hide_banner -loglevel panic -c:v copy -c:a copy -bsf:a aac_adtstoasc -copyts outfile.mp4
for ".flv" sources:
ffmpeg -i inputfile -y -hide_banner -loglevel panic -movflags +faststart -c:v copy -strict -2 -q:a 100 outfile.mp4

**Comment by TarkusLV** [comment]
Thanks for your feedback.  Coincidentally (?) my favorite free lossless editor (LosslessCut) was updated yesterday to include an option for fixing videos with incorrect duration, and it works pretty fast.  Normally just a few seconds per video, with no conversion necessary.

**Comment by jdoedev123** [comment]
@TarkusLV  No problem. Looking up LosslessCut on github it is a GUI front end for ffmpeg. It may take all the messy details of multimedia file fixing with ffmpeg from the end user.

**Comment by Gujal00** [comment]
@dobbelina this issue can be closed
