### ISSUE TITLE
Better fixed add-on?

### ISSUE THREAD

**Issue by lukehansford** [dobbelina/repository.dobbelina#4]
Here is the add-on I have working mostly.

I got a few of the fixes from the original Dev by pm and used the latest porntrex fix.

It has all scene categories working and has some missing from .65 like yespornplease.

[plugin.video.uwcfixedv3.zip](https://github.com/dobbelina/repository.dobbelina/files/2824372/plugin.video.uwcfixedv3.zip)

**Comment by jdoedev123** [comment]
Thanks. I took a quick look at both new test releases of 19.02.02
No release is perfect so far.
Luke's uwcfixedv3 is about the same as my own personal test version
dobelina's  just released 1.1.65 in this repository is missing budloi's available fix for  WatchXXXFree ( https://pastebin.com/HWjKLMPc ) and is missing YesPornPlease available in 1.1.64.
I haven't had time to do a full code diff but otherwise they seem quite similar.

**Comment by deanogers** [comment]
The addon won’t update keeps saying 1.1.65 won’t bring up 1.1.66 can u help please

**Comment by ohmichael** [comment]
Daftsex don’t work
