### ISSUE TITLE
Chaturbate Favorites

### ISSUE THREAD

**Issue by ChoccyStarfish** [dobbelina/repository.dobbelina#584]
Hi, When saving a favourite which has been already saved, you get the pop-up option to update the name and photo, but alas it doesn't update the photo, this would be very useful indeed. Thank you.

**Comment by ErosVece** [comment]
Do you have 'Auto-refresh Webcam images' enabled in the addon settings?
If not, enable it....change the favorite, and reload the favorites.

Also, you can go to Chaturbate and click on 'Refresh Chaturbate images'

**Comment by ChoccyStarfish** [comment]
Thanks for your reply, but when I enable "Auto-Refresh Webcam Images" and then go to a chaturbate category, it just "spins" and doesn't populate the cams, when I turn off "Auto-Refresh Webcam Images" then it populates with the cams. I seem to remember on the old "whitecream" add-on you could just add the person again and it would add the updated image, any ideas? Any help is appreciated.

**Comment by ErosVece** [comment]
What happens when you go to Chaturbate and click on 'Refresh Chaturbate images'?
Does it also spins for a while?

I just tried on Kodi Leia (18.9) and Matrix (19.1), both Windows, and I have no problems.
There hasn't changed much in functionality between Ultimate Whitecream and Cumination, with cleaning webcam thumbnails.

Maybe you have many many cached Chaturbate thumbnails, so it takes a while?

What system/kodi version are you running?
Can you post a full debug log when you try to enter Chaturbate with auto-refresh enabled?

**Comment by ChoccyStarfish** [comment]
ErosVece, I've just got it working, thank you very much, to be honest, I backed up my favourites, reinstalled Kodi and Cumination again, added my favourites and now "Auto-Refresh Webcam Images" works perfectly as you said, I think I had to many thumbnails etc, anyway all sorted now, thank you for your time.
