### ISSUE TITLE
Segregation please

### ISSUE THREAD

**Issue by imurreflection** [dobbelina/repository.dobbelina#585]
Hi Cumination looks quite cluttered. Can we please have sites assigned to different categories like..Cam, Animation etc..

**Comment by ErosVece** [comment]
NO!

Because, you can do that yourself :)

![image](https://user-images.githubusercontent.com/37535332/130249363-b9aae8cd-bf81-476e-ac32-27becd679380.png)

![image](https://user-images.githubusercontent.com/37535332/130249440-84c88a85-1c85-4a8d-ad8d-e31012d98654.png)

![image](https://user-images.githubusercontent.com/37535332/130249497-42d5936f-2001-4844-9aca-9346847f375f.png)

![image](https://user-images.githubusercontent.com/37535332/130249565-429fca2f-4d48-4c5c-a4a7-dd3d06515ac3.png)

![image](https://user-images.githubusercontent.com/37535332/130249595-79a3bfbd-2851-4a3f-a831-bae6e4e2f98b.png)

Now, go to the new Animation folder

![image](https://user-images.githubusercontent.com/37535332/130249658-23ffdd7f-20f0-4454-b0ca-641dbecfb548.png)

**Comment by ErosVece** [comment]
You can do that for any site or folder.
For example, you can create a list called Anal, and add the Anal category from Pornhub, Porntrex and others there.

In my example above, I've added the Hentai categories from Pornhub and Porntrex:
![image](https://user-images.githubusercontent.com/37535332/130250145-2df9395f-ca48-473e-bfce-cee29abe40a1.png)

**Comment by ErosVece** [comment]
Also, what is cluttered about every sitename in alphabetical order?
UWC was way more cluttered, with sites in random order in each section.

Also, the reason Cumination doesn't have sections is less liability :)

**Comment by TarkusLV** [comment]
One of the things I like best about Cumination is the flexibility to create your own sections.  Takes a bit more work to set up initially, but very much worth it.

**Comment by imurreflection** [comment]
Hi ErosVece. Thanks for the wonderful and detailed explanation. I was not aware of this feature. I will create sections as required and will revert if I encounter any issue. Thanks again. Closing the issue now.
