### ISSUE TITLE
Uflash Error 

### ISSUE THREAD

**Issue by Buddha2400** [dobbelina/repository.dobbelina#706]
Every time I try to go into uflash I get an error message and it won’t open at all. In which I included a screenshot of the error message. If you need the actual log files you’re gonna have to tell me where exactly it is located at. 

![E867D137-6F22-45FB-B1C5-3E806D4B6870](https://user-images.githubusercontent.com/33353171/153692061-884386a0-cb4b-4590-b49f-98e644aa4efb.jpeg)

![00AC10C5-FE7A-4DFD-994C-1FF5A2E507DD](https://user-images.githubusercontent.com/33353171/153692063-7f7e07d5-82cb-42db-a1b0-a238c8afbc54.jpeg)

![BBE39302-7D8E-44C8-A54B-C66C0E7880A3](https://user-images.githubusercontent.com/33353171/153692065-58060dcf-5760-4601-bbb2-d3ae75ec72ac.jpeg)

**Comment by Buddha2400** [comment]
I guess the developers don’t care about trying to help people who are seeking and asking for help

**Comment by TarkusLV** [comment]
You didn't even give them a full day.  They do this on their own time for free.  Get over your sense of entitlement.  If you think volunteers owe you something (immediately too!), you need a reality check.

**Comment by Buddha2400** [comment]
No I’m not entitled I’m just sick and tired of people that ignore people who are seeking help. That’s all period.

**Comment by Buddha2400** [comment]
Plus I have a very very very low tolerance for BS.

**Comment by EvelK1203** [comment]
Put a ticket in for a refund...

**Comment by Buddha2400** [comment]
If neither of y’all can help please keep your comments to the peanut gallery. People like y’all are the reason why I would prefer to be alone on this planet.

**Comment by Buddha2400** [comment]
I’m using an android box. And plus this issue wasn’t addressed because they added a new site onto the ad one on which the site does not load. Obviously you didn’t take the time to read what I had posted. Like I said before if you’re not trying to help keep your comments to yourselves. And you don’t know what I did yes I Google on finding  logs but I don’t know which log do they need so that’s why I said if they need the logs tell me exactly where they are at.

**Comment by Buddha2400** [comment]
Yeah I may be in some ways adapt to programming. I’m not that’s why I’m asking for help.

**Comment by Gujal00** [comment]
Yes, this seems to be an Android specific issue. Works fine in Windows and Linux. Need more time to look at this issue
Anyway uflash is not yet released, it is not in the released version 1.1.33. Have to get this working before the next release

**Comment by Gujal00** [comment]
> Oh ok. Then I don’t get why add uflash.py if it’s not ready yet.
It is added for people like you to test.

**Comment by Buddha2400** [comment]
Then it should be noted for testing use only. That will help to stop confusion.

**Comment by dobbelina** [comment]
Tested in browser, no cloudflare.
Errors out on my Windows 10 64bit rig.
https://paste.kodi.tv/ubifatuyat.kodi

**Comment by Buddha2400** [comment]
Would there be a fix anytime soon?

**Comment by dobbelina** [comment]
Fixed, and will be in the 1.1.34 release https://github.com/dobbelina/repository.dobbelina/commit/d26ef70d3064dc420d20cbebda75a62957670841

**Comment by PuttingYouOnBlast** [comment]
@Buddha2400 
"I guess the "free loaders" don’t care about "saying, "'Hey, the fix worked. Thank you. I can crawl back into the rock I'm living in." @Buddha2400 don't even respond.  You definitely showed your true character. Honestly.... Please look into some counseling. 
& for the other cat @imurreflection , who tried to give him advice, even though you're part of the problem with the devs. Suggesting that, "Please understand that these developers have their own life also..this is not a paid platform mate. " meanwhile, you asked @dobbelina, to release the next update because you're inpatient for it. Or even better, your reaching out to the devs who are not repairing the issues fast enough because you're IMPATIENT. Oh but let me add, always suggesting that this site is the "best", for the hundredth time. I've checked some of your suggested sites, they have potato cam videos. This is FUCKING ridiculous. How about getting your hand off your cock & try to learn Python coding & try to contribute. Take the initiative to learn on your own & not be hand fed!!! . As for the dev that implemented the new lines in the uflash.py file. It didn't work for me, I'm using the Nvidia Shield (Android). Prior to your new edits, I actually changed line 37 & 74 to html = utils.getHtml2. After those changes, I did get the list to show up BUT when I clicked on the link, it wouldn't play. So, I checked the error in the log. I couldn't figure it out. After the new changes have been implemented, it still didn't show the list (directory). I wound up going back to line 37 & 74 and changing html = utils.getHtml to html = utils.getHtml2, then changing line 107 html = utils.getHtml(url, site.url) to html = utils.getHtml(urll) because of the error. The videos started playing.  As, I was double checking right now, I noticed that, that line 107 has been removed completely. So... Yeah, this is how we learn from the devs. I'm now going to try to figure it out.  So @dobbelina & the devs who contribute to this addon, thank you. @dobbelina , I honestly feel that you need to make the issues section more restricted. They have to provide a debug log file & also give them an idea on how to figure out if the site they are trying to recommend has DMCA information, running on their phones/laptop etc device their using. Another platform that is out of the Kodi platform. Alot of these users think they know how to manage Kodi BUT they don't.  On another note, I think you should also have a separate directory for those who want to contribute a "custom site".  I'm personally using your CrazyShit custom site that you provided & feel that you should have a section for those who want to contribute they're own "custom site". I think it would be beneficial & might limit the constant "site requests" you get.  @dobbelina & the devs who have contributed/repaired/gave advice etc. etc. Thank you for your advice & knowledge you have implemented. I'm always looking to learn..... Thank you...

**Comment by Gujal00** [comment]
@PuttingYouOnBlast 
Have a play with EFukt custom site too
_Originally posted by @Gujal00 in https://github.com/dobbelina/repository.dobbelina/issues/407#issuecomment-1013651486_

**Comment by PuttingYouOnBlast** [comment]
Thanks @Gujal00

**Comment by PuttingYouOnBlast** [comment]
> @PuttingYouOnBlast 
> Have a play with EFukt custom site too
> _Originally posted by @Gujal00 in https://github.com/dobbelina/repository.dobbelina/issues/407#issuecomment-1013651486_
> 

Hey @Gujal00 ... I definitely recalled  that site a long time ago. It's similar to Crazyshit. I have a dry sense of humor & can deal with those extreme  videos BUT I honestly feel we have a lot of  snow flakes lurking. So going back to the custom sites, should a warnng be implemented to sites like this? I do!!!

**Comment by imurreflection** [comment]
@PuttingYouOnBlast...

You are a dog with sick mentality. First if you look at @gujal00 response in the issue above, you will see that he has mentioned the OP to wait for 48 hours and my request for aadition of sites or releasing updates are made after "Days.' if you call this 'Impatient" let it be..Also, even after the issue has been addressed or not, i have always been patient and also closed issues proactively.  As I said only a sick man like you can like Efukt or Crazyshit and I agree they are full UHD sites....and listen you fucking asshole, the developer who initiated the process of learning Python provided the same link which was given earlier whereas it was supposed to be a Tut. I can also see that you have made lot of changes in the code and I am sure, there are many commits by you but I don't see anything..You actually need a good counselling session on how to interact with anyone.. guess, this is what you are born n brought up with..do a self retrospection..are people around you are happy with you...
