### ISSUE TITLE
Netfapx

### ISSUE THREAD

**Issue by deanogers** [dobbelina/repository.dobbelina#711]
Videos won’t update on kodi can u fix please

**Comment by DJMix-I-Can** [comment]
The newest videos have been updated. If they don't upload any new content, the Netfapx won't update. When you posted this two days ago, the update list was consistent. There were no new updates. If they don't update, of course the Cumination wouldn't update. Since your post, it has been updated. Didn't it? If you want to compare the Cumination addon to the actual content from the site. Go here https://netfapx.com/?orderby=newest If it's different after numerous days, yeah, you can have an issue.
