### ISSUE TITLE
Myfreecams

### ISSUE THREAD

**Issue by onknight** [dobbelina/repository.dobbelina#74]
It seems my free cams is getting smarter
They keep blocking the feed and and telling me to call myfreecam support
It seems they're seeing my IP address

**Comment by DJMix-I-Can** [comment]
Yup, Someone decided to e-mail tech support and this was their response. "Our systems have detected you may be using a third party script to perform automated actions on MyFreeCams.
Scripts such as this are not supported, and will cause your IP address to be blocked from accessing the site." At first, it seems like it works but after 3 minutes, you'll get an image stating
"Unusually activity has been detected from your IP address. Contact support@myfreecams.com with error code #37122 Myfreecams.com"

**Comment by onknight** [comment]
Anyway to fix this ?

**Comment by 12asdfg12** [comment]
Probably mfc implemented a protection against recording.

**Comment by onknight** [comment]
ya there are alot bots on that site

**Comment by jdoedev123** [comment]
UWC must be doing something different from the normal web access to allow them to detect and block it. I know we are faking being a mobile device, I assume for a simpler API. For me sometimes it works sometimes I am blocked in Kodi for days.

**Comment by DJMix-I-Can** [comment]
While I was watching The Boys on my Shield, I decided to try the site again on my laptop. I clicked on one cam and it ran for ten minutes without getting that message. I stopped that cam and clicked on another cam and it ran for 25 minutes before she logged off. I didn't receive a message. It could've been a trial run by MFC. Did they stop it because of their bottom line or analyzing their test run? @jdoedev123 as I stated before, I'm not that familiar with coding but have some tech experience. Can they detect that key strokes are not being made when accessing their cam girls? When I googled what that error meant, there was a user who admitted to recording their live streams for hours.  Just my two "still trying to comprehend" cents...

**Comment by onknight** [comment]
So this has been my experience so far
If I watch online through normal memes of MFC it's fine
But once I try using the white cream add-on I get the contact MFC black
If I didn't try to use up browser and watch the girls I get that same contact MFC air

So then I just change my IP and it's fine until I use the add-on again
