### ISSUE TITLE
cumination issue: https://voyeur-house.life do not work....

### ISSUE THREAD

**Issue by p060477** [dobbelina/repository.dobbelina#753]
hi, this new site added to cumination do not work....the oldest https://voyeur-house.to works but this new added at this moment do not work...this bug is only for me...??...or others have same issue as mine..??
thxs in adv
 cheers

**Comment by dobbelina** [comment]
1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. provide the url from step 7 here

Any bugreports without logfile will be deleted.

**Comment by p060477** [comment]
should be more easly and speedly if you just test the site...as you have done for all the issues opened here...the latestes is about avple site...
thxs so much indeed
cheers

**Comment by Gujal00** [comment]
@p060477 You didnt follow the instructions above to generate a complete debug log. Cant work with log snippets

**Comment by p060477** [comment]
hi, this is the kodi.log i've in my kodi 19.1
and this is the way i have -always- uploaded my logs here...
and i've -always- have a reply/help...
so for me is so strange this -new- way....
all the info you require are in...
as, i re-underline-, on my every past logs uploaded here...
pls this helps
thxs soi much for yr comprehension
have a nice week end
cheers

**Comment by dobbelina** [comment]
voyeur-house.life works for me on both kodi 18.9 & 19.4 so a complete
logfile is needed to pinpoint the issue.
Lots of stuff is missing in the provided logfile and it doesn't look to have been made in debug mode.

**Comment by p060477** [comment]
hi dobbelina,
here it is:
[https://paste.kodi.tv/jazosimepo](url)
and also attached a screenshoot cause i do not have a smartphone for the QR code
hope this helps
thxs again
have a nice
![Immagine](https://user-images.githubusercontent.com/12773559/164887737-f871cfe3-1216-4806-8314-766e655b360f.jpg)
 week end

**Comment by Gujal00** [comment]
Something strange with your Kodi install
`DEBUG <general>: <urlopen error [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1128)`
All I can suggest is install Kodi 19.4 portable instead of the 19.1 that your using and try with cumination only without other addons installed to start with

**Comment by p060477** [comment]
done
nothing changed
same frustratring error/bug/issue
https://paste.kodi.tv/caduherina

**Comment by dobbelina** [comment]
@p060477 can you access https://voyeur-house.life with your browser?

**Comment by p060477** [comment]
of course...
i've just tried again 
in the home page there is also written:
dear user, we start uploading all videos in new server be patient please

**Comment by Gujal00** [comment]
Looks like the CDN in your location is not updated yet, so unless you can see videos in browser, you wont on the addon

**Comment by DJMix-I-Can** [comment]
Just a thought, troubleshooting mentality.... You're on a Windows 10 PC. When dobbelina mentioned to check the site on your browser, it was a good suggestion because you would've had the same issue. You didn't though.... So now, the next thing is to check your Windows firewall & Windows Defender, is it blocking Kodi? Are you using a VPN? Did you do any new Windows updates?

**Comment by p060477** [comment]
but why this is the only site in cumination that did not work in the add on...??
i repeat and re-underline that all the others work fine in cumination...
so for me this is an issue in cumination and between it and this only particular site
this is way i've opened this issue
and also why i'm wasting so much time in lots of proofs...as for ex. uploading a -debug log-
thing that i repeat always i've really did not in the past...in the past i simply upload here the first log i create here and dobbelina fixed the issue...
so really really strange...

**Comment by Gujal00** [comment]
It is because the issue seems to be specific to you, neither me nor dobbelina can replicate your issue, so asking you for debug logs.

So unless the webpage looks like below on a browser, it is not going to work inside cumination
There is no "dear user, we start uploading all videos in new server be patient please" message
![image](https://i.imgur.com/D2E8aSX.png)

**Comment by p060477** [comment]
here it is:

![Immagine](https://user-images.githubusercontent.com/12773559/165491287-8eaee07f-bb23-4846-9d6f-15809291d25b.jpg)

i'm really not saying lies...and do not want to waste yr time..or mine...

this is a issue , i repeat, between ONLY this site and yr cumination add on

so check yr file and try to solve/fix

thxs so much for yr kind attention

have a nice week

cheers

**Comment by Gujal00** [comment]
There is no "dear user, we start uploading all videos in new server be patient please" message in my screenshot and it is in your screenshot. So it is specific yo your region and that is why it is not working for you. Nothing can be done in the mean time

**Comment by p060477** [comment]
but why is easly reaching in my browser...?..i'm not using any proxy or vpn...
so the -region- should not interfeer -if- i'm able to see,i repeat, in my browser..
cause the image i've uploaded speak so clearly...i'm easly able to view the site..
so the matter, i repeat, is in yr kodi add on....otherwise i won't be able to see the site in my browser too...
so i think that you could do more than nothing...
;)

**Comment by DJMix-I-Can** [comment]
@p060477 I know you and I have interacted before. Hope all is well. I understand this issue is getting annoying to you. @dobbelina @Gujal00 are requiring more info through the debug file because it will give them a thorough command of every function you're doing within Kodi. Yes, it wasn't like that before BUT in all honestly, it should've been. Users are still posting issues as, this site is not working. That's it, no other information. What is not working? Is the directory of the site not showing up? Or it is but there's no images? Or everything loads up but when you click on the link it doesn't play? Or everything loads up, it plays BUT when you click on the Categories, Models, or whatever doesn't load up? They don't provide that info. Those little details will help them where to go to instead of going through the whole site code. That is why the required debug log has been implemented. As for your situation, I also received the "Dear User" information on my Windows laptop. Regardless, the site worked on my Android device. I have no problems viewing the directory & playing within the Cumination adddon.
I know @dobbelina suggested to check your browser BUT which browser did you actually check. Did you check on your PC browser, phone browser while still connected to your wifi or were you off the wifi? Did you check while you were away from you house and using your phones ISP? Those little details make a difference. Addition to this, do you have a router? Did you configure the DNS or did you leave it to default, which goes through your ISP. Personally, on my router I changed the DNS to Google. You could also use Cloudflares DNS IP. In your debug file, I noticed you were using Windows 10. Have you checked that Windows Defender or Windows Firewall is not blocking anything? @p060477 These are trouble shooting sequences we usually do in order to figure out what the problem is.  @Gujal00 , @dobbelina & I don't have a problem accessing the website via the Cumination addon. It's not an addon issue, it's a situation from your end. It happens. Try this, Close Kodi. Once it's closed, go to O:\Kodi_19.4\KodiPortable\App\Kodi\portable_data\temp and delete everything from there. Now go to O:\Kodi_19.4\KodiPortable\App\Kodi\portable_data\userdata\Thumbnails and delete everything from there. Now go to O:\Kodi_19.4\KodiPortable\App\Kodi\portable_data\userdata\Database & delete the textures13.db file. Once you do that, shut down your laptop. Now unplug your modem & router for about 5 minutes. Re-plug, let your modem & router restart. Once everything has booted up, now turn your laptop/PC on. Let Windows boot up, once it's done, open Kodi and try voyeur-house.life again. It is NOT a Cumination issue, if it was, everyone would be having the issue. They as well as I would try to help you with your issue but you need to understand, the more info we get, the faster they and I could try to help. Hope it works out for you...

**Comment by p060477** [comment]
hi to you all, first let me thxs forever all your efforts and yr patience with me
i tried step by step what [DJMix-I-Can](https://github.com/DJMix-I-Can) has clearly detailed in his post
but the issue is still there....
for me is so strange that i'm quite able to reach the site in browser but not in kodi...everytime was the opposite....
so for me is strange but i've steal lots of yr time and patience too...
so i pray you to beg my pardon and to apologize me..
you have been so very very gentle and kind
and patienceable...
thxs again fro the deep of my heart
cheers

**Comment by DJMix-I-Can** [comment]
@p060477 I understand the mystery of your issues you're dealing with. This is the last thing I could think of as it is a weird situation. The only reason why I still think about it is because you're using Windows.  So, I'm trying to think of windows issues that could cause this issue. Have you had a virus, spam ware, hard-drive or SSD issues? Could it have been infected or corrupted? Who knows, that is why we troubleshoot. I don't know why I didn't think of this before but try this last thing. Close Kodi & delete this file under O:\Kodi_19.4\KodiPortable\App\Kodi\portable_data\addons\plugin.video.cumination\resources\lib\sites\reallifecam.py. Now download it again from Github , https://github.com/dobbelina/repository.dobbelina/blob/master/plugin.video.cumination/resources/lib/sites/reallifecam.py and replace it into your KodiPortable folder. Restart Kodi & see if it works, if it doesn't, I can't think of anything else. Hope it works out. Be well..

**Comment by dobbelina** [comment]
If you have a third party firewall, try disabling it temporarily and try to run 
Cumination.
If you have another device, Android phone etc try installing kodi on that and give it a go.

**Comment by p060477** [comment]
hi to you all, first i re-thank you again for all, i'm running a pc desktop win 10 home 64, i've only this pc no others unfurtunately,
the tries done with browers,edge,firefox,chrome,opera,brave,waterfox works fine, also if i do not disable the antivirus and firewall,
i really have stolen too much of yr precious time
i repeat you have been so very very gentle and kind
and patienceable...
thxs again from the deep of my heart
and i pray you to apologize me again
cheers
