### ISSUE TITLE
cumination --netflixporno

### ISSUE THREAD

**Issue by demex2008** [dobbelina/repository.dobbelina#761]
Hallo
the netflixporn fix will Not Work on
categories-- Transsexual , Shemale.
can you Look at this
mfg.

hello could you maybe add site&date added to favorites
mfg.

**Comment by Bigdane14** [comment]
Downloads won’t work!!! Damn it.
Can you guys/girls please fix…

**Comment by DJMix-I-Can** [comment]
The directories Transexual & Shemale do load. I'm assuming your issue is that they don't play.  The reason they don't play is because majority of them are only using one hoster. That host is Netu, the video host is not supported. If you go to their webpage via a browser, you could see that they only have Netu as an option. On the other hand if you come across a video like this one, https://netflixporno.net/adult/ts-cheaters/ You'll see that Netu, Streamzz, Youdbox & DoodStream are your options. When you click on it in Cumination, you won't see Netu but will get the other three options in order to view the video. It did play & was able to download. I'm using Android.

**Comment by WVSJJ** [comment]
![Screenshot 2022-05-27 at 17 27 19](https://user-images.githubusercontent.com/104718689/170731284-c2322c98-466d-4e0d-bb51-de30998f5fb3.jpg)
Hi, 

I have added a screenshot with the log, for a failing site regarding Netflixporno. It looks like there is something going wrong with the code or the pulling of modules. Could you take a look?

Last Error in Log:
- NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
Error Type: <class 'TypeError'>
Error Contents: expected string or bytes-like object
Traceback (most recent call last):
File "/addons/plugin.video.cumination/default.py", line 155, in <module>
sys.exit(main()
File "/addons/plugin.video.cumination/default.py", line 148, in main
url dispatcher.dispatch(mode, queries)
File "/addons/plugin.video.cumination/resources/lib/url_dispatcher.py",line 119, in dispatch
cls.func registry[mode](*args, **kwargs)
File "/addons/plugin.video.cumination/resources/lib/sites/netflixporno.py",line 39, in Main
List(https://netflixporno.net/")
File "/addons/plugin.video.cumination/resources/lib/sites/netflixporno.py", line 50, in List
match=re.compile('<article[^>]+>.+?<a href="([^"+)". *?src="([^"+)".+?Title">([^"]+)</div', re.DOTALL I
re.IGNORECASE).findall(listhtml)
TypeError: expected string or bytes-like object

Also in text now.

**Comment by dobbelina** [comment]
A fix will be in the next 1.1.43 release https://github.com/dobbelina/repository.dobbelina/commit/7022e1f7bb1f1efa07536fbc29ad59a0405ffb57
