### ISSUE TITLE
Cumination - xhamster site doesn't work

### ISSUE THREAD

**Issue by Stane1983** [dobbelina/repository.dobbelina#782]
### Bug reports:

xHamster site doesn't work, throws error when trying to open video

### OS environment
Android TV 9, Sony Bravia TV

1. Install Kodi Logfile Uploader addon from Offcial Kodi Repository under Program add-ons.
2. Enable Debug logging, (Settings - System - Logging - Enable Debug Logging)
3. Restart Kodi (Important)
4. Go into Cumination and open the site (wait for the error message)
5. Come out of cumination
6. Disable Debug logging, (Settings - System - Logging - Enable Debug Logging off)
7. launch Kodi Logfile uploader and upload your log. This will give you a url
8. https://paste.kodi.tv/qecawaqufa

Any bugreports without logfile will be deleted.

**Comment by Gujal00** [comment]
A couple of issues from your log
```
INFO <general>: CAddonMgr::FindAddons: script.module.resolveurl v5.1.28 installed
INFO <general>: CAddonMgr::FindAddons: script.module.resolveurl.xxx v2.1.23 installed
```
Those two versions do not work together
```
DEBUG <general>: ADDONS: update check: addonID = script.module.resolveurl / Origin =  / Version = 5.1.28
DEBUG <general>: ADDONS: update check: addonID = script.module.resolveurl.xxx / Origin = repository.dobbelina / Version = 2.1.23
```
resolveurl.xxx is latest version and coming correctly from dobbelina repository but resolverl itself is very old and not setup to update from any repository
Fix resolveurl on your install so that it gets updated from dobbelina repository and it will update to 5.1.68 and will then work correctly

**Comment by Stane1983** [comment]
@Gujal00 thanks, no idea how that other version got installed. Anyway, it's fixed now :)

**Comment by Gujal00** [comment]
Please close the issue if it is working correctly
