### ISSUE TITLE
JavBangers playback issue

### ISSUE THREAD

**Issue by Cr4zyM0f01** [dobbelina/repository.dobbelina#848]
### Bug Reports
Hi I seem to be having a problem with JavBangers, when I try skipping forward on videos I'm thrown back to the main menu. It used to work fine before the latest JavBangers fix. I tried with 3 videos skipping to 40 minutes, not sure if that helps. Again thank you for everything you guys do here, hopefully there is a fix for this.

### OS Environment
Kodi V19.4 Matrix, XBOX-SERIES S

### LogFile
https://paste.kodi.tv/atomusewix

**Comment by DJMix-I-Can** [comment]
Someone else had the same issue about a month ago. They didn't provide a debug log or state what type of device they were using. I suggested that it could be a cache issue on their device at that time but never got a response.
I use the Nvidia Shield and as the previous user who had that issue, I couldn't replicate it. I tried it again & it's fine for me.
This is my advancedsettings.xml file since you also have one... Try changing the readfactor to 24 instead of 8 first. Close Kodi, clear the cache, restart your XBox and test it out. See if that works out. If not, try copying my settings completely and see if that helps out.... Just my two cents....
<advancedsettings>
    <cache>
        <memorysize>209715200</memorysize>
        <readfactor>24</readfactor>
        <buffermode>2</buffermode>
        <curlretries>2</curlretries>
        <curlclienttimeout>20</curlclienttimeout>
        <curllowspeedtime>15</curllowspeedtime>
    </cache>
    <network>
            <disablehttp2>true</disablehttp2>
    </network>
</advancedsettings>

**Comment by Cr4zyM0f01** [comment]
> Someone else had the same issue about a month ago. They didn't provide a debug log or state what type of device they were using. I suggested that it could be a cache issue on their device at that time but never got a response. I use the Nvidia Shield and as the previous user who had that issue, I couldn't replicate it. I tried it again & it's fine for me. This is my advancedsettings.xml file since you also have one... Try changing the readfactor to 24 instead of 8 first. Close Kodi, clear the cache, restart your XBox and test it out. See if that works out. If not, try copying my settings completely and see if that helps out.... Just my two cents.... ![Advanced](https://user-images.githubusercontent.com/35236592/188761642-0e3572ad-53a4-4492-aba1-c9e3e576e52e.jpg)

Hi, thanks for the reply. I tried both your suggestions but unfortunately the problem is still happening for me. I suppose I'll have to just live with it for now. Thanks again for you help I really appreciate it.
