### ISSUE TITLE
Site Filter

### ISSUE THREAD

**Issue by EvelK1203** [dobbelina/repository.dobbelina#854]
Is it possible to add a site filter to enable/disable specific sites from main site listing? The site listing is getting quite bulky, Not complaining about that, the hard work is much appreciated!

Thanks!

**Comment by Gujal00** [comment]
The main site listing is a collection of all the sites.
You can make your own custom lists with your preferred sites from the main list using the `Create Custom List` option in the main menu

**Comment by DJMix-I-Can** [comment]
I'm going to assume as of right now.... You open Cumination & the only thing you see is Sites, Favourite Videos, Download Folder & Create Custom List.  You usually click on the Sites folder and scroll to your favourite sites & hating that you have to scroll through all the sites. Is that correct? If so, this is what you do & what I did.  Go to the Sites folder & go to whatever site you like. Don't enter it, just highlight it & then long press in order to get the context menu. Once you get the context menu, you should have the following options, About Site, Add item to..., Addon Settings & Set this view as default. Click on Add item to... Then select Main Menu... This will be added to the main menu when you click on Cumination.  For example,  I love big natural breasts.... I went to XHamster, categories, clicked B, then went to Big Natural Breasts, long pressed to get the context menu and added it to my main menu. I no longer have to go through all the steps.... Give it a try..

**Comment by EvelK1203** [comment]
Thanks Guys, I wasn't aware of how that feature functioned. That will work great!
