### ISSUE TITLE
Numerous Issues

### ISSUE THREAD

**Issue by DJMix-I-Can** [dobbelina/repository.dobbelina#91]
I'm going to post this here temporarily. I would like for you guys to test out each issue (to confirm) before creating issues for them. I had some weird issues as I was testing it out on my Windows Laptop. Some issues that occurred in Windows, did not occur on Android. I did make sure it was on the same version and also transferred the py file from the Win laptop to the android to confirm I wasn't bugging.
These are the current issues that I have not successfully solved or haven't looked into.
Thanks.

Scenes
1.  Pornvibe-Alot of categories don't load. Mostly non Czech sites. Videos in categories don't play.
2. Porndoe-Channels directory doesn't load.

Tubes
1. VPorn-Categories doesn't load.

**Comment by jdoedev123** [comment]
Scenes 1 and 2 should be fixed in version 93 fixes for Porn00 and PornAQ. Thanks for all your work.

**Comment by dobbelina** [comment]
> @dobbelina Yeah I didn't expect you to include the partials into an update. Just did what I can and hoped someone else could fix the other issues.

Much obliged

**Comment by 12asdfg12** [comment]
@DJMix-I-Can
I didn't see anything unusual in the log files except for the "Could not open file" error.
Resolved URLs look good.
What happens when you try to play a resolved link (https: //cnx.datoporn.co / .....) in Firefox?
Can you play videos from datoporn from the website ? maybe something is blocking your connection (your ISP or your IP is banned)


4. HD Zog-Search fixed
[hdzog.zip](https://github.com/dobbelina/repository.dobbelina/files/3610409/hdzog.zip)

5. Mr. Sexe-Stars directory fixed
[mrsexe.zip](https://github.com/dobbelina/repository.dobbelina/files/3610523/mrsexe.zip)

6. Czech3x/HD - videos hosted on hqq.tv (netu.tv), which is broken in Resolveurl (since last year), probably is better to be removed from uwc

7. k18 doesn't worth to be fixed, new links are from pornhub, no original content, old links (mostly) does not work

**Comment by DJMix-I-Can** [comment]
When I try to play directly from the website, I click on play, get the ad pop-up, I close it, go back to the original main window, and the center play button now has an exclamation mark. On the left top corner of the video it says, "Cannot load M3U8: Cross domain access denied."
If I copy and paste that url from the log, I get a blank white page and on the top left corner "error_wrong_ip"
I also thought that my IP must be banned. It did work before but it was a while ago since I really don't use it at all. Oh well, no biggie. That's why I wanted you guys to test it.
Thanks...

**Comment by jdoedev123** [comment]
DJMix-I.-Can, Re: your last post. Perhaps the URL playback in browser is related to not having the correct referrer URL which dataporn usually requires in the header. 
For example with the wget tool the following usually works to download a video:
wget  --no-check-certificate   -c  URL  --referer=https://dataporn.co

In a web browser you should be able to use something like:
URL|Referer=http://datoporn.co

**Comment by dobbelina** [comment]
I forgot to remove k18  in the latest v1.1.94, I'll remove it in the next release.

**Comment by wwilesco** [comment]
Has anybody else noticed that mark as read no longer works in UWC. This has happened since updating to Kodi 18

**Comment by bbqyes** [comment]
Ive made an account and it still wont let me watch private videos? Am i doing something wrong?

**Comment by dobbelina** [comment]
> 
> 
> Ive made an account and it still wont let me watch private videos? Am i doing something wrong?

If for porntrex, it's not working at the moment, needs a fix.

**Comment by 12asdfg12** [comment]
fixed speedporn, mango, buba, hclips, spankbang:
[xx.zip](https://github.com/dobbelina/repository.dobbelina/files/3666670/xx.zip)

**Comment by 12asdfg12** [comment]
for spankbang i put the old file in the archive, that's the good one:
[spankbang.zip](https://github.com/dobbelina/repository.dobbelina/files/3678134/spankbang.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12!

All changes committed to v.1.1.96
