### ISSUE TITLE
Queue or "Play From Here" problems. 

### ISSUE THREAD

**Issue by vile80r** [dobbelina/repository.dobbelina#92]
I've had a strange issue with this addon for a while now. 

It happens if I add videos to a queue and then play the queue.
or if I do a search, or pick a category, essentially if there is a list of videos there in the addon and I bring up the context menu and choose 'Play From Here'

The videos won't play like they do when I do this in other addons. 

The expected result is for one video to play and when it's finished the next video will start and repeat until the end of the queue or list of videos is reached. 

The result I'm getting is the video will load and immediately, within the first few seconds it will load the next video and play that for a few seconds and then load the next. This repeats until the end or I cancel it. 

I cannot figure out why it loads the next queued video before the prior video has complete or why it happens so rapidly. 

This is definitely an issue unique to this addon.

**Comment by 12asdfg12** [comment]
Kodi has two functions for video playback: xbmc.Player().Play and xbmcplugin.setResolvedUrl.
UWC uses xbmc.Player().Play and it seems like this is causing the issue.
I modified utils.py, so that "Play from here" will use the xbmcplugin.setResolvedUrl function for playback.

Also i added  the option '|verifypeer=false' proposed by @ruinernin.

[utils.zip](https://github.com/dobbelina/repository.dobbelina/files/3643139/utils.zip)

**Comment by dobbelina** [comment]
Thanks 12asdfg12 !

I'll incorporate it.
