### ISSUE TITLE
Custom site issue

### ISSUE THREAD

**Issue by Spanktacular** [dobbelina/repository.dobbelina#978]
I have changed entries on the motherless.zip files to reflect a custom site. I have verified the URLs are functional. On my Android box, I browse to the zip to install it, then enable it. When I attempt to enter the sites list, I'm greeted with an error. If I disable the custom site, I'm able to view the list of sites, minus my custom of course.

Suggestions?

**Comment by dobbelina** [comment]
What are the entries you have changed on the motherless.zip file?

**Comment by DJMix-I-Can** [comment]
@imurreflection He stated that he modified the Motherless.zip file in order to get his personal custom site. He is not looking to install motherless.
@Spanktacular As I stated to some else who tried to install a custom site. You cannot just modify the URLS (motherless.com to your preferred website) from an existing Motherless python file in order to get it up and running. If you take a look at all of the site python files, they're all different. All of the coding pertains to that particular website.

**Comment by imurreflection** [comment]
I apologize. I thought he was looking to get the custom site installed

**Comment by Spanktacular** [comment]
> What are the entries you have changed on the motherless.zip file?

In every file where motherless was found I changed it to maturetube. Apparently, that doesn't work?

May I request a custom site file for this site from someone who knows how to do it?

**Comment by dobbelina** [comment]
What site?

**Comment by dobbelina** [comment]
[Motherless](https://github.com/dobbelina/repository.dobbelina/issues/407#issuecomment-1146847664)

closing thread.

**Comment by Gujal00** [comment]
`Mature Tube` is part of the AWM Network and has been added to cumination in the last release
